export const FETCH_PROPERTIES_START = "FETCH_PROPERTIES_START";
export const FETCH_PROPERTIES_FAIL = "FETCH_PROPERTIES_FAIL";
export const FETCH_PROPERTIES_SUCCESS = "FETCH_PROPERTIES_SUCCESS";

export const FETCH_VEHICLES_START = "FETCH_VEHICLES_START";
export const FETCH_VEHICLES_FAIL = "FETCH_VEHICLES_FAIL";
export const FETCH_VEHICLES_SUCCESS = "FETCH_VEHICLES_SUCCESS";
